10:33:50,76 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:41601/], count 0
10:33:50,77 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:41601/], count 0
10:33:50,140 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:33:50,235 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:34:37,9 root INFO START TRIAL WITH HOLO
10:35:47,9 root INFO Human finished in: 65.99107003211975
10:35:47,32 root INFO Step 1: 66.01385450363159
10:36:24,114 root INFO Human finished in: 33.04620051383972
10:36:24,114 root INFO Step 2: 33.046658754348755
10:37:08,321 root INFO Human finished in: 39.34890913963318
10:37:27,456 root INFO Human finished in: 58.48333668708801
10:37:27,476 root INFO Step 3: 58.5040328502655
10:38:05,376 root INFO Human finished in: 32.60393500328064
10:38:05,376 root INFO Step 4: 32.60441064834595
10:43:33,710 rospy.core INFO signal_shutdown [atexit]
10:43:33,719 rospy.internal INFO topic[/rosout] removing connection to /rosout
10:43:33,719 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
10:43:33,720 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:41601/
10:43:33,720 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:41601/
10:43:33,721 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:46417 (http://simone-Aspire-V3-772G:41601/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

10:43:33,721 rospy.impl.masterslave INFO atexit
10:43:33,724 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:46417 (http://simone-Aspire-V3-772G:41601/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

10:48:56,160 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:36277/], count 0
10:48:56,161 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:36277/], count 0
10:48:56,251 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:48:56,257 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:50:05,961 rospy.core INFO signal_shutdown [atexit]
10:50:05,973 rospy.internal INFO topic[/rosout] removing connection to /rosout
10:50:05,973 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
10:50:05,973 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:36277/
10:50:05,973 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:36277/
10:50:05,975 rospy.impl.masterslave INFO atexit
10:50:17,218 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:44159/], count 0
10:50:17,223 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:50:17,225 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:44159/], count 0
10:50:17,420 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:51:05,825 root INFO START TRIAL WITH HOLO
10:51:36,761 rospy.core INFO signal_shutdown [atexit]
10:51:36,777 rospy.internal INFO topic[/rosout] removing connection to /rosout
10:51:36,777 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
10:51:36,779 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:44159/
10:51:36,779 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:44159/
10:51:36,779 rospy.impl.masterslave INFO atexit
10:51:36,780 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:46045 (http://simone-Aspire-V3-772G:44159/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

10:52:08,478 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:46041/], count 0
10:52:08,479 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:52:08,488 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:46041/], count 0
10:52:08,664 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:52:37,75 root INFO START TRIAL WITH HOLO
10:53:19,451 root INFO Human finished in: 39.83841109275818
10:53:19,479 root INFO Step 1: 39.8658390045166
10:57:11,430 rospy.core INFO signal_shutdown [atexit]
10:57:11,438 rospy.internal INFO topic[/rosout] removing connection to /rosout
10:57:11,438 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
10:57:11,439 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:46041/
10:57:11,439 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:46041/
10:57:11,442 rospy.impl.masterslave INFO atexit
10:57:19,225 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:35247/], count 0
10:57:19,225 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:35247/], count 0
10:57:19,235 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:57:19,435 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:57:27,357 rospy.core INFO signal_shutdown [atexit]
10:57:27,367 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:44537 (http://simone-Aspire-V3-772G:35247/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

10:57:27,368 rospy.internal INFO topic[/rosout] removing connection to /rosout
10:57:27,368 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
10:57:27,368 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:35247/
10:57:27,368 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:35247/
10:57:27,368 rospy.impl.masterslave INFO atexit
10:59:13,102 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
10:59:13,105 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:45123/], count 0
10:59:13,106 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:45123/], count 0
10:59:13,202 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
10:59:44,964 root INFO START TRIAL WITH HOLO
11:00:02,21 rospy.core INFO signal_shutdown [atexit]
11:00:02,44 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:00:02,44 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:00:02,45 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:45123/
11:00:02,45 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:45123/
11:00:02,45 rospy.impl.masterslave INFO atexit
11:00:11,45 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:45337/], count 0
11:00:11,45 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:45337/], count 0
11:00:11,93 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:00:11,290 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:00:35,273 rospy.core INFO signal_shutdown [atexit]
11:00:35,285 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:35115 (http://simone-Aspire-V3-772G:45337/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

11:00:35,287 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:35115 (http://simone-Aspire-V3-772G:45337/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

11:00:35,287 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:45337/
11:00:35,288 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:00:35,289 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:00:35,289 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:45337/
11:00:35,289 rospy.impl.masterslave INFO atexit
11:03:11,886 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:03:11,951 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:43421/], count 0
11:03:11,954 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:43421/], count 0
11:03:12,57 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:03:31,451 root INFO START TRIAL WITH HOLO
11:06:47,925 rospy.core INFO signal_shutdown [atexit]
11:06:47,931 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:06:47,931 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:06:47,936 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:43421/
11:06:47,936 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:43421/
11:06:47,936 rospy.impl.masterslave INFO atexit
11:13:39,352 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:38529/], count 0
11:13:39,353 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:38529/], count 0
11:13:39,404 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:13:39,498 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:14:21,606 root INFO START TRIAL WITH HOLO
11:14:33,504 rospy.core INFO signal_shutdown [atexit]
11:14:33,507 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:14:33,507 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:14:33,507 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:38529/
11:14:33,508 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:38529/
11:14:33,508 rospy.impl.masterslave INFO atexit
11:15:14,381 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:35779/], count 0
11:15:14,382 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:35779/], count 0
11:15:14,393 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:15:14,578 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:15:32,28 root INFO START TRIAL WITH HOLO
11:18:55,383 rospy.core INFO signal_shutdown [atexit]
11:18:55,393 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:18:55,393 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:18:55,393 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:35779/
11:18:55,394 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:35609 (http://simone-Aspire-V3-772G:35779/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

11:18:55,394 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:35779/
11:18:55,395 rospy.topics ERROR Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

11:18:55,395 rospy.impl.masterslave INFO atexit
11:21:22,998 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:21:23,70 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:35621/], count 0
11:21:23,74 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:35621/], count 0
11:21:23,176 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:21:54,665 root INFO START TRIAL WITH HOLO
11:22:49,269 root INFO Human finished in: 52.10916352272034
11:22:49,270 root INFO Step 1: 52.109976291656494
11:23:04,331 root INFO Human finished in: 10.31630825996399
11:23:13,310 root INFO Step 2: 19.295204877853394
11:23:57,31 root INFO Human finished in: 37.18280076980591
11:23:57,32 root INFO Step 3: 37.183231830596924
11:24:38,750 root INFO Human finished in: 33.26129937171936
11:24:38,751 root INFO Step 4: 33.262216567993164
11:24:58,366 root INFO Reset count: 0
11:24:58,367 root INFO END TRIAL
11:24:58,480 root INFO Collisions: 6
11:25:07,98 root INFO START TRIAL WITHOUT HOLO
11:25:23,119 root INFO Human finished in: 14.505262613296509
11:25:28,345 root INFO Step 1: 19.731566190719604
11:25:56,685 rospy.core INFO signal_shutdown [atexit]
11:25:56,694 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:25:56,695 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:25:56,695 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:35621/
11:25:56,696 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:35621/
11:25:56,696 rospy.impl.masterslave INFO atexit
11:25:56,697 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:45603 (http://simone-Aspire-V3-772G:35621/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

11:30:40,324 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:30:40,402 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:36835/], count 0
11:30:40,405 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:36835/], count 0
11:30:40,499 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:31:08,337 root INFO START TRIAL WITH HOLO
11:32:03,986 root INFO Human finished in: 42.590837717056274
11:32:03,987 root INFO Step 1: 42.59131860733032
11:32:17,152 root INFO Human finished in: 9.577747106552124
11:32:25,838 root INFO Step 2: 18.263548374176025
11:32:56,678 root INFO Reset count: 0
11:32:56,678 root INFO END TRIAL
11:32:57,90 root INFO Collisions: 0
11:33:03,92 root INFO START TRIAL WITH HOLO
11:33:15,597 root INFO Human finished in: 11.324115991592407
11:33:23,786 root INFO Step 1: 19.513004302978516
11:33:43,296 root INFO Human finished in: 15.284449577331543
11:33:46,293 root INFO Step 2: 18.281018257141113
11:34:14,195 root INFO Human finished in: 24.070387601852417
11:34:14,196 root INFO Step 3: 24.070876359939575
11:34:38,112 root INFO Human finished in: 20.79602837562561
11:34:38,133 root INFO Step 4: 20.81675124168396
11:35:41,520 rospy.core INFO signal_shutdown [atexit]
11:35:41,530 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:35:41,531 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:35:41,531 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:36835/
11:35:41,531 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:36835/
11:35:41,531 rospy.impl.masterslave INFO atexit
11:37:13,929 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:37:14,35 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:37:14,40 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:38431/], count 0
11:37:14,48 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:38431/], count 0
11:37:37,352 root INFO START TRIAL WITH HOLO
11:38:05,125 root INFO Step 1: 25.82214856147766
11:38:05,126 root INFO Human finished in: 25.822601556777954
11:38:32,997 root INFO Human finished in: 25.13239598274231
11:38:32,998 root INFO Step 2: 25.132869243621826
11:38:48,875 root INFO Human finished in: 13.122689485549927
11:38:54,297 root INFO Step 3: 18.544269323349
11:39:30,378 root INFO Human finished in: 22.933430671691895
11:39:30,378 root INFO Step 4: 22.933794260025024
11:53:02,143 rospy.core INFO signal_shutdown [atexit]
11:53:02,152 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:53:02,152 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:53:02,152 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:38431/
11:53:02,152 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:38431/
11:53:02,152 rospy.impl.masterslave INFO atexit
11:54:53,526 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40731/], count 0
11:54:53,527 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40731/], count 0
11:54:53,546 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:54:53,747 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:54:55,550 rospy.core INFO signal_shutdown [atexit]
11:54:55,565 rospy.internal INFO topic[/rosout] removing connection to /rosout
11:54:55,565 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
11:54:55,565 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40731/
11:54:55,565 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40731/
11:54:55,565 rospy.impl.masterslave INFO atexit
11:55:30,491 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40645/], count 0
11:55:30,493 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40645/], count 0
11:55:30,554 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
11:55:30,656 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
11:56:23,479 root INFO START TRIAL WITH HOLO
12:00:08,93 rospy.core INFO signal_shutdown [atexit]
12:00:08,95 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:00:08,96 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:00:08,96 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40645/
12:00:08,96 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40645/
12:00:08,97 rospy.impl.masterslave INFO atexit
12:00:08,97 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:42481 (http://simone-Aspire-V3-772G:40645/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
OSError: [Errno 9] Bad file descriptor

12:00:20,474 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:00:20,566 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:00:20,581 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:33353/], count 0
12:00:20,583 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:33353/], count 0
12:01:07,979 rospy.core INFO signal_shutdown [atexit]
12:01:07,987 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:01:07,987 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:01:07,988 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:33353/
12:01:07,989 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:33353/
12:01:07,989 rospy.impl.masterslave INFO atexit
12:01:07,990 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:44063 (http://simone-Aspire-V3-772G:33353/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

12:01:07,990 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:44063 (http://simone-Aspire-V3-772G:33353/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

12:35:58,954 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:35:59,4 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:35:59,9 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:36511/], count 0
12:35:59,10 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:36511/], count 0
12:37:19,86 root INFO START TRIAL WITH HOLO
12:37:22,580 rospy.core INFO signal_shutdown [atexit]
12:37:22,590 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:37:22,590 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:37:22,590 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:36511/
12:37:22,591 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:36437 (http://simone-Aspire-V3-772G:36511/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

12:37:22,593 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:36511/
12:37:22,593 rospy.impl.masterslave INFO atexit
12:37:22,594 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:36437 (http://simone-Aspire-V3-772G:36511/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

12:37:30,230 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:41093/], count 0
12:37:30,232 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:41093/], count 0
12:37:30,259 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:37:30,461 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:37:32,48 rospy.core INFO signal_shutdown [atexit]
12:37:32,56 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:37:32,56 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:37:32,56 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:41093/
12:37:32,58 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:41093/
12:37:32,58 rospy.impl.masterslave INFO atexit
12:37:51,376 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:39753/], count 0
12:37:51,377 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:39753/], count 0
12:37:51,397 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:37:51,494 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:38:13,533 root INFO START TRIAL WITH HOLO
12:39:28,110 root INFO Human finished in: 64.8653769493103
12:39:28,111 root INFO Step 1: 64.86583876609802
12:39:55,949 root INFO Human finished in: 24.9274845123291
12:39:55,949 root INFO Step 2: 24.92788028717041
12:42:01,116 root INFO Human finished in: 49.10406494140625
12:42:01,117 root INFO Step 3: 49.105037212371826
12:42:35,73 root INFO Human finished in: 27.675596714019775
12:42:35,73 root INFO Step 4: 27.67607283592224
12:45:21,860 rospy.core INFO signal_shutdown [atexit]
12:45:21,868 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:45:21,868 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:45:21,869 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:39753/
12:45:21,870 rospy.topics ERROR Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

12:45:21,870 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:35841 (http://simone-Aspire-V3-772G:39753/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

12:45:21,871 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:39753/
12:45:21,871 rospy.impl.masterslave INFO atexit
12:45:21,875 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:35841 (http://simone-Aspire-V3-772G:39753/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

12:46:19,457 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:40679/], count 0
12:46:19,457 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:40679/], count 0
12:46:19,490 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
12:46:19,689 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
12:46:42,462 root INFO START TRIAL WITH HOLO
12:49:26,791 root INFO Human finished in: 142.03824710845947
12:49:26,792 root INFO Step 1: 142.0387179851532
12:50:49,39 root INFO Human finished in: 77.95019912719727
12:50:59,335 root INFO Human finished in: 88.24630737304688
12:50:59,336 root INFO Step 2: 88.24709439277649
12:51:25,495 root INFO Human finished in: 20.31037163734436
12:51:25,496 root INFO Step 3: 20.310784578323364
12:51:50,387 root INFO Human finished in: 18.033748388290405
12:51:51,567 root INFO Step 4: 19.21445918083191
12:59:43,783 rospy.core INFO signal_shutdown [atexit]
12:59:43,795 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:44285 (http://simone-Aspire-V3-772G:40679/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

12:59:43,796 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:44285 (http://simone-Aspire-V3-772G:40679/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

12:59:43,796 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:40679/
12:59:43,797 rospy.internal INFO topic[/rosout] removing connection to /rosout
12:59:43,797 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
12:59:43,797 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:40679/
12:59:43,797 rospy.impl.masterslave INFO atexit
13:03:23,611 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:03:23,622 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:03:23,630 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:46633/], count 0
13:03:23,632 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:46633/], count 0
13:03:59,355 root INFO START TRIAL WITH HOLO
13:05:44,858 rospy.core INFO signal_shutdown [atexit]
13:05:44,867 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:05:44,867 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:05:44,868 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:46633/
13:05:44,868 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:46633/
13:05:44,869 rospy.impl.masterslave INFO atexit
13:10:59,587 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:10:59,661 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:10:59,694 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:38629/], count 0
13:10:59,698 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:38629/], count 0
13:11:40,559 rospy.core INFO signal_shutdown [atexit]
13:11:40,568 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:36611 (http://simone-Aspire-V3-772G:38629/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

13:11:40,568 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:36611 (http://simone-Aspire-V3-772G:38629/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

13:11:40,568 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:38629/
13:11:40,568 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:38629/
13:11:40,570 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:11:40,570 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:11:40,570 rospy.impl.masterslave INFO atexit
13:12:31,698 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:45601/], count 0
13:12:31,698 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:45601/], count 0
13:12:31,727 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:12:31,926 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:12:56,624 root INFO START TRIAL WITH HOLO
13:19:02,455 rospy.core INFO signal_shutdown [atexit]
13:19:02,462 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:19:02,462 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:19:02,464 rospy.internal ERROR Unable to initiate TCP/IP socket to simone-Aspire-V3-772G:38443 (http://simone-Aspire-V3-772G:45601/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
rospy.exceptions.TransportInitError: remote error reported: node shutting down

13:19:02,469 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:45601/
13:19:02,469 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:45601/
13:19:02,469 rospy.impl.masterslave INFO atexit
13:19:02,470 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:38443 (http://simone-Aspire-V3-772G:45601/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
ConnectionResetError: [Errno 104] Connection reset by peer

13:19:56,585 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:19:56,652 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:42873/], count 0
13:19:56,655 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:42873/], count 0
13:19:56,748 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:20:30,589 rospy.core INFO signal_shutdown [atexit]
13:20:30,596 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:20:30,596 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:20:30,596 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:42873/
13:20:30,597 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:42873/
13:20:30,597 rospy.impl.masterslave INFO atexit
13:22:01,835 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:22:01,852 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:34573/], count 0
13:22:01,857 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:34573/], count 0
13:22:01,954 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:22:16,86 rospy.core INFO signal_shutdown [atexit]
13:22:16,97 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:22:16,98 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:22:16,98 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:34573/
13:22:16,98 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:34573/
13:22:16,98 rospy.impl.masterslave INFO atexit
13:22:16,99 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:37269 (http://simone-Aspire-V3-772G:34573/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 561, in connect
    self.write_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 641, in write_header
    sock.setblocking(1)
OSError: [Errno 9] Bad file descriptor

13:22:16,100 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:37269 (http://simone-Aspire-V3-772G:34573/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
ConnectionRefusedError: [Errno 111] Connection refused

13:22:22,300 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:22:22,310 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:22:22,312 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:35939/], count 0
13:22:22,314 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:35939/], count 0
13:22:47,318 rospy.core INFO signal_shutdown [atexit]
13:22:47,331 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:22:47,331 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:22:47,331 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:35939/
13:22:47,331 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:35939/
13:22:47,331 rospy.impl.masterslave INFO atexit
13:22:47,338 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:46287 (http://simone-Aspire-V3-772G:35939/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/noetic/lib/python3/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
rosgraph.network.ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

13:22:54,588 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:22:54,637 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:22:54,645 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:45139/], count 0
13:22:54,651 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:45139/], count 0
13:23:23,92 root INFO START TRIAL WITH HOLO
13:25:40,786 rospy.core INFO signal_shutdown [atexit]
13:25:40,792 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:25:40,792 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:25:40,792 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:45139/
13:25:40,793 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:45139/
13:25:40,793 rospy.impl.masterslave INFO atexit
13:32:23,714 rospy.internal INFO topic[/step_done] adding connection to [http://simone-Aspire-V3-772G:42249/], count 0
13:32:23,715 rospy.internal INFO topic[/collision_count] adding connection to [http://simone-Aspire-V3-772G:42249/], count 0
13:32:23,740 rospy.internal INFO topic[/next_step] adding connection to [/server_endpoint], count 0
13:32:23,945 rospy.internal INFO topic[/rosout] adding connection to [/rosout], count 0
13:32:59,120 root INFO START TRIAL WITH HOLO
13:35:32,955 root INFO Human finished in: 138.38252711296082
13:35:32,958 root INFO Step 1: 138.38569140434265
13:36:03,30 root INFO Step 2: 25.38596224784851
13:36:03,30 root INFO Human finished in: 25.386443614959717
13:36:39,681 root INFO Human finished in: 33.29645609855652
13:36:39,682 root INFO Step 3: 33.29731893539429
13:37:10,779 root INFO Human finished in: 12.48508596420288
13:37:16,694 root INFO Step 4: 18.39989686012268
13:38:25,759 rospy.core INFO signal_shutdown [atexit]
13:38:25,767 rospy.internal INFO topic[/rosout] removing connection to /rosout
13:38:25,767 rospy.internal INFO topic[/next_step] removing connection to /server_endpoint
13:38:25,769 rospy.internal INFO topic[/step_done] removing connection to http://simone-Aspire-V3-772G:42249/
13:38:25,769 rospy.internal INFO topic[/collision_count] removing connection to http://simone-Aspire-V3-772G:42249/
13:38:25,770 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:43463 (http://simone-Aspire-V3-772G:42249/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

13:38:25,770 rospy.impl.masterslave INFO atexit
13:38:25,770 rospy.internal WARNING Unknown error initiating TCP/IP socket to simone-Aspire-V3-772G:43463 (http://simone-Aspire-V3-772G:42249/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

